---
- name: OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - mysql
    - setup
    - service
    - config

# We need to check if mysql is already installed or not,
# in order to perform first-time configuration.
- name: Check if mysql is installed
  shell: test -x {{ mysql_binary }}
  ignore_errors: True
  register: mysql_is_installed

# We also need to check if mysql is running.
- name: Check if mysql is running
  command: service mysqld status
  ignore_errors: True
  register: mysql_is_running

# Os specific installation.
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"

- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"

# Geeral service configuration.
- include: config.yml
  tags:
    - mysql
    - config

# First-time configuration.
- include: bootstrap.yml
  when: mysql_is_installed|failed

# Service behaviour.
- include: service.yml
  tags:
   - mysql
   - service

# Integration with external services.
- include: external.yml
  tags:
   - mysql
   - external

